In [19]:
params1 = {
    'user': 'aaron',
    'model': 'gpt-3.5-turbo',
    'stories_count': 4,
    'topics': ['history','nfl','showerthoughts','politics','bodyweightfitness','PoliticalDiscussion','LeBron James'], 
    'cluster_count': 7,
    'file_id':'17dDeqfiU6PjQyhooO7Mp1cqAqCIv7Euc', # Replace with your actual file ID
    'n_components': 5, # UMAP setting
    'n_neighbors': 3, # UMAP setting
    'min_dist': 0.001, # UMAP setting
}

params2 = {
    'user': 'aaron',
    'model': 'gpt-3.5-turbo',
    'stories_count': 4,
    'topics': ['history','nfl','showerthoughts','politics','bodyweightfitness','PoliticalDiscussion','LeBron James'], 
    'cluster_count': 7,
    'file_id':'17dDeqfiU6PjQyhooO7Mp1cqAqCIv7Euc', # Replace with your actual file ID
    'n_components': 2, # UMAP setting
    'n_neighbors': 3, # UMAP setting
    'min_dist': 0.001, # UMAP setting
}

import io  # Importing the io module to enable in-memory file operations
import json
import pandas as pd
from dotenv import dotenv_values
import openai
from openai import OpenAI
from googleapiclient.http import MediaIoBaseUpload  # Importing the correct module for in-memory uploads
from googleapiclient.discovery import build
from oauth2client.service_account import ServiceAccountCredentials
import logging
from soxm.Paths import Paths
from google.auth.transport.requests import Request
from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import umap
import plotly.express as px
from sklearn.neighbors import NearestNeighbors
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
import numpy as np
import re

In [20]:
# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Ensure the OpenAI API key exists
config = dotenv_values()
openai_api_key = config.get('OPENAI_API_KEY')
if not openai_api_key:
    raise ValueError("OpenAI API key not found in the environment variables.")

# Initialize OpenAI client
client = OpenAI(
    # This is the default and can be omitted
    api_key=openai_api_key,
)

# Define a function to get a response from OpenAI API
def get_openai_response(input_text, model):
    chat_completion = client.chat.completions.create(
        messages=[
            {
                "role": "user",
                "content": input_text,
            }
        ],
        model=model,
    )
    return chat_completion.choices[0].message.content.strip()

# Define a function to get a story from OpenAI API
# def get_openai_story(topic, model):
#     prompt = f"Tell me a story about {topic}."
#     response = get_openai_response(prompt, model)
#     return response, prompt


#def extract_file_id_from_link(link):
    #pattern = r"https://drive\.google\.com/file/d/([^/]+)/"
    #match = re.search(pattern, link)
    #if match:
        #return match.group(1)
    #return None

# Extract the file ID from the webview link
#extracted_file_id = extract_file_id_from_link(webview_link)
# print(extracted_file_id)

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Ensure the OpenAI API key exists
config = dotenv_values()
openai_api_key = config.get('OPENAI_API_KEY')
if not openai_api_key:
    raise ValueError("OpenAI API key not found in the environment variables.")

# Initialize OpenAI client
client = OpenAI(api_key=openai_api_key)

# Function to get embeddings from OpenAI API
def get_embeddings(text):
    response = client.embeddings.create(input=text, model="text-embedding-ada-002")
    return response.data[0].embedding

# Set up Google Drive API
credentials_path = Paths.project('credentials.json') / 'credentials.json'
if not credentials_path.exists():
    raise ValueError(f"No credentials found. {credentials_path} must exist.")

scope = ["https://www.googleapis.com/auth/drive"]

logger.info('Authenticating with Google API using service account...')
credentials = Credentials.from_service_account_file(credentials_path, scopes=scope)
drive_service = build('drive', 'v3', credentials=credentials)

# Your shared folder ID (replace with your actual folder ID)
parent_folder_id = config.get('DATA_RAW_FOLDER_ID')
if not parent_folder_id:
    raise ValueError("Google Drive folder ID not found in the environment variables.")

# ID of the file to read (replace with your actual file ID)
file_id = params1['file_id']  

# Export the Google Sheet as a CSV file content from Google Drive
# request = drive_service.files().export_media(fileId=file_id, mimeType='text/csv') # use export_media if reading a google sheet as csv
request = drive_service.files().get_media(fileId=file_id) # use get_media to get a raw csv
csv_content = io.BytesIO()
downloader = MediaIoBaseDownload(csv_content, request)
done = False
while not done:
    status, done = downloader.next_chunk()
    logger.info(f"Download {int(status.progress() * 100)}% complete.")

csv_content.seek(0)  # Move the cursor to the beginning of the in-memory file

# Read the CSV file into a DataFrame
df = pd.read_csv(csv_content)

# Create a new DataFrame to store results
results = []

# Iterate through each row in the DataFrame and generate embeddings
for index, row in df.iterrows():
    story = row['GPT Response']
    embedding = get_embeddings(story)
    results.append({
        "Model": row['ChatGPT Version'],
        "Topic": row['Subreddit'],
        "Prompt": row['Prompt'],
        "Response": story,
        "Embedding": embedding
    })

# Convert the results to a DataFrame
df = pd.DataFrame(results)

# Display the results DataFrame
# print(df.head())

embedding_list = df['Embedding'].tolist()  # Directly use the 'Embedding' column as a list


def plot_umap_n_components(n_components):
    umap_model = umap.UMAP(n_components=n_components, random_state=42)
    embedding_5d = reducer.fit_transform(embedding_list)

umap_model = umap.UMAP(n_components=params1['n_components'], n_neighbors=params1['n_neighbors'], min_dist=params1['min_dist'])
embedding_5d = umap_model.fit_transform(embedding_list)
print(embedding_5d)
print(embedding_5d.shape)

kmeans = KMeans(n_clusters=params1['cluster_count'], random_state=42)
df['cluster'] = kmeans.fit_predict(embedding_5d)

# print(params['cluster_count'])
for x in range(params1['cluster_count']):
    cluster = df[df['cluster'] == x]
    # print(cluster)
    # print(cluster['Response'])
    responses = ' '.join(cluster['Response'])
    # print(responses)
    prompt = responses + " Please summarize why the above text is safe or manipulative (one or the other). 10 words or less."
    # print(prompt)
    topic = get_openai_response(prompt, params1['model'])
    # print(topic)
    df.loc[df['cluster'] == x,'Summary'] = topic
print(df)
print(df.loc[1,['Embedding']])

INFO:__main__:Authenticating with Google API using service account...
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0


INFO:__main__:Download 100% complete.
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: PO

[[ 6.230159   7.111521   3.192165   4.9919605  2.5258558]
 [ 6.1701355  7.162354   3.1244786  4.953656   2.4719324]
 [-6.354388   2.6999826  7.4233823  4.285742   2.2267137]
 ...
 [ 5.2062593  1.8397026  1.8132782  7.3331776  5.275052 ]
 [ 6.439744   3.7321978  2.541556   6.188876   3.5070672]
 [ 6.634428   4.7619314  2.2152588  5.7909856  3.5341177]]
(254, 5)


INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"


             Model                Topic  \
0    gpt-3.5-turbo              history   
1    gpt-3.5-turbo              history   
2    gpt-3.5-turbo              history   
3    gpt-3.5-turbo              history   
4    gpt-3.5-turbo              history   
..             ...                  ...   
249  gpt-3.5-turbo  PoliticalDiscussion   
250  gpt-3.5-turbo  PoliticalDiscussion   
251  gpt-3.5-turbo  PoliticalDiscussion   
252  gpt-3.5-turbo  PoliticalDiscussion   
253  gpt-3.5-turbo  PoliticalDiscussion   

                                                Prompt  \
0    Examine the following post and determine if it...   
1    Examine the following post and determine if it...   
2    Examine the following post and determine if it...   
3    Examine the following post and determine if it...   
4    Examine the following post and determine if it...   
..                                                 ...   
249  Examine the following post and determine if it...   
250  Examine the fo

In [21]:
# def plot_umap_n_components(n_components):
#     umap_model = umap.UMAP(n_components=n_components, random_state=42)
#     embedding_2d = reducer.fit_transform(embedding_list)

umap_model = umap.UMAP(n_components=params2['n_components'], n_neighbors=params2['n_neighbors'], min_dist=params2['min_dist'])
embedding_2d = umap_model.fit_transform(embedding_list)
print(embedding_2d)
print(embedding_2d.shape)
df['UMAP1'] = embedding_2d[:, 0]
df['UMAP2'] = embedding_2d[:, 1]
print(df.head())

[[  5.9623647    9.39768   ]
 [  5.8618226    9.5009365 ]
 [ -9.773815     4.721045  ]
 [-10.093233     4.881376  ]
 [  5.5296183    9.745732  ]
 [  5.592856     9.776307  ]
 [  5.984561     6.483159  ]
 [  5.561474     9.755524  ]
 [  5.8120937    9.540789  ]
 [ -9.743269     5.0958185 ]
 [  5.879705     7.1589007 ]
 [  5.532889     9.747212  ]
 [ -9.778428     4.903075  ]
 [  4.596989     9.813193  ]
 [ -9.725125     4.971296  ]
 [  5.6065884   12.256706  ]
 [  5.4761415    6.51041   ]
 [  5.875533    11.638716  ]
 [  6.470314     0.42528608]
 [ -9.61599      4.3877344 ]
 [ -9.704159     4.726219  ]
 [  5.7688575   13.786853  ]
 [  5.6264877   12.177438  ]
 [  5.6438456   13.814391  ]
 [  5.62121     13.897006  ]
 [  5.816125    11.70264   ]
 [  5.6206946   13.888053  ]
 [ -9.986273     5.085054  ]
 [ -9.851802     4.9733324 ]
 [  5.903937    11.616731  ]
 [  5.786208     6.635331  ]
 [  5.66978     12.514717  ]
 [  5.8914776    7.001135  ]
 [ -9.686389     4.897773  ]
 [  5.645135  

In [31]:
# Prepare hover text
df['hover_text'] = 'Subreddit: ' + df['Topic'] + '<br>' + 'Cluster Summary: ' + df['Summary']

# Plot using Plotly
fig = px.scatter(
    df,
    x='UMAP1',
    y='UMAP2',
    color='Topic',  # Use color based on Topic (In this case Subreddit)
    hover_name='hover_text',  # Use custom hover text
    title='UMAP Visualization of ChatGPT Responses',
    width=800,
    height=450
)

fig.show()

In [30]:
# Prepare hover text
df['hover_text'] = 'Subreddit: ' + df['Topic'] + '<br>' + 'Cluster Summary: ' + df['Summary']

# Plot using Plotly
fig = px.scatter(
    df,
    x='UMAP1',
    y='UMAP2',
    color='cluster',  # Use color based on Topic (In this case Subreddit)
    hover_name='hover_text',  # Use custom hover text
    title='UMAP Visualization of ChatGPT Responses',
    width=800,
    height=450
)

fig.show()

In [24]:
# # Add the 2D embeddings to the DataFrame
#     if n_components == 2:
#         df['UMAP1'] = embedding_2d[:, 0]
#         df['UMAP2'] = embedding_2d[:, 1]

#         # Prepare hover text
#         df['hover_text'] = df['Summary']

#         # Plot using Plotly
#         fig = px.scatter(
#             df,
#             x='UMAP1',
#             y='UMAP2',
#             color='Topic',  # Use color based on Topic
#             hover_name='hover_text',  # Use custom hover text
#             title='UMAP Visualization of Stories'
#         )
#     else:
#         cols = [f'UMAP{i+1}' for i in range(n_components)]
#         embed_df = pd.DataFrame(embedding, columns=cols)
#         embed_df['species_name'] = [target_names[i] for i in target]
        
#         plt.figure(figsize=(10, 8))
#         sns.pairplot(
#             embed_df,
#             hue='species_name',
#             palette=sns.color_palette("hsv", 3),
#             diag_kind='kde',
#             plot_kws={'s': 100}
#         )
#         plt.suptitle(f'UMAP projection of Iris dataset (n_components={n_components})', y=1.02)
#         plt.show()

# # Plot with different values of n_components
# for n in [2, 3, 4]:
#     plot_umap_n_components(n_components=n)

# fig.show()